### ISSUE TITLE
Refactor how data feeds configuration file is retrieved, validated and normalized

### ISSUE THREAD

**Issue by Tommytrg** [witnet/data-feeds-explorer#197]
We could refactor how to data feeds configuration file is read, normalized and validated.

We can also review the normalized configuration type to check if it is still valid or we are just maintaining the old configuration format.

**Comment by gabaldon** [comment]
This was fixed in commit: [e84bd90416496dae5eaeb0453aad64b69f8198db](https://github.com/witnet/data-feeds-explorer/commit/e84bd90416496dae5eaeb0453aad64b69f8198db)

**Comment by Tommytrg** [comment]
This issue was not fixed. We are still using a normalization based on how we retrieved the data before the configuration was read from the file in the new format. But for now, we can continue doing it in that way because the refactor doesn't seem significant enough compare it with the cost to do implement it
